---
title: "COPC"
---
Create, Observe, Participate, Consume

## Purpose
These four words are components to how I sometimes plan but most often reflect on my day. Each day is an opportunity to experience each area. The approach is influenced by the balanced virtues in Stoicism. A day in balance has balanced the experiences. So let's talk about each:

## Components  
### Create
Creation is the most active component of the 4 components. It is the act of making a new thing from other things. It may include knowledge but is self directed. It requires an individual to contribute to a goal. It can and mostly does include failure. Attempts count for this component Examples of creation:  

* Writing blog post 
* Cooking dinner 
* Planning a trip 
* Sketching a diagram 
* Taking a picture 

### Observe
Observation is the act of paying attention to the world around us. It involves being present and aware of our surroundings, experiences, and interactions. It allows us to gather information, gain insights, and learn from our environment. Examples of observation include:  

- Watching a sunset 
- Listening to a conversation 
- Studying nature 
- Analyzing data 

### Participate
Participation is the act of actively engaging in activities, events, or discussions. It involves being involved, contributing, and taking part in various aspects of life. Examples of participation include: 

- Playing a sport 
- Attending a conference 
- Volunteering for a cause 
- Participating in a group discussion 

### Consume
Consumption is the act of taking in or using something. It involves receiving, absorbing, or utilizing resources, information, or experiences. Examples of consumption include:  

- Reading a book 
- Watching a movie 
- Eating a meal 
- Listening to music 


## How to use COPC
TODO